export default [
    {
        id: "barbieA",
        image: "assets/images/barbieA.png",
        title: "Barbie 35th Anniversary Brunette - Special Edition (1994)",
        price: 52000,
        stock: 5,
        quantity: 0,
        total:  0,
    }, 
    {
        id: "barbieB",
        image: "assets/images/barbieB.png",
        title: "Barbie Morning Sun Princess - Celestial Collection (2000)",
        price: 35000,
        stock: 5,
        quantity: 0,
        total:  0,
    },
    {
        id: "barbieC",
        image: "assets/images/barbieC.png",
        title: "Baywatch Barbie - Original Mattel (1995)",
        price: 25000,
        stock: 5,
        quantity: 0,
        total:  0,
    },
    {
        id: "barbieD",
        image: "assets/images/barbieD.png",
        title: "France Barbie - Dolls of The World Collection (2008)",
        price: 42000,
        stock: 5,
        quantity: 0,
        total:  0,
    },
    {
        id: "barbieE",
        image: "assets/images/barbieE.png",
        title: "Chilean Barbie - Dolls of the World Collector Series (1997)",
        price: 20000,
        stock: 5,
        quantity: 0,
        total:  0,
    },
    {
        id: "barbieF",
        image: "assets/images/barbieF.png",
        title: "Barbie as Dorothy - In The Wizard of Oz (1999)",
        price: 30000,
        stock: 5,
        quantity: 0,
        total:  0,
    },
    {
        id: "barbieG",
        image: "assets/images/barbieG.png",
        title: "Patriot Barbie - American Stories Series Collector Edition (1997)",
        price: 28000,
        stock: 5,
        quantity: 0,
        total:  0,
    },
    {
        id: "barbieH",
        image: "assets/images/barbieH.png",
        title: "Fountain Mermaid Barbie - Original Mattel (1993)",
        price: 25000,
        stock: 5,
        quantity: 0,
        total:  0,
    },
    {
        id: "barbieI",
        image: "assets/images/barbieI.png",
        title: "Swedish Barbie - Dolls of the World Collection 20th Anniversary (2000)",
        price: 20000,
        stock: 5,
        quantity: 0,
        total:  0,
    },
    {
        id: "barbieJ",
        image: "assets/images/barbieJ.png",
        title: "Barbie Sixties Fun - Special Edition (1997)",
        price: 30000,
        stock: 5,
        quantity: 0,
        total:  0,
    },
    {
        id: "barbieK",
        image: "assets/images/barbieK.png",
        title: "Barbie Happy Holidays - Special Edition (1996) ",
        price: 118000,
        stock: 5,
        quantity: 0,
        total:  0,
    },
    
    {
        id: "barbieL",
        image: "assets/images/barbieL.png",
        title: "Elvis Presley Barbie - Barbie Signature (2021) ",
        price: 65000,
        stock: 5,
        quantity: 0,
        total:  0,
    }
]
